# Travis configuration guide for R language:


language: r
sudo: false
cache: packages


before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
use_bioc: false
bioc_required: false
